#!/bin/bash
# Project: Crankshaft
# This file is part of Crankshaft project.
# Copyright (C) 2025 OpenCarDev Team
#
#  Crankshaft is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Crankshaft is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Crankshaft. If not, see <http://www.gnu.org/licenses/>.

set -e

case "$1" in
    configure)
        # Create crankshaft user if it doesn't exist
        if ! id -u crankshaft > /dev/null 2>&1; then
            useradd --system --no-create-home --shell /bin/false crankshaft
        fi
        
        # Set proper ownership for config directory
        chown -R crankshaft:crankshaft /etc/crankshaft
        chmod 755 /etc/crankshaft
        chmod 644 /etc/crankshaft/crankshaft.json
        
        echo "Crankshaft Core installed successfully"
        echo "To start the service manually: crankshaft-core"
    ;;
esac

exit 0
