#!/bin/bash
# Project: Crankshaft
# This file is part of Crankshaft project.
# Copyright (C) 2025 OpenCarDev Team
#
#  Crankshaft is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Crankshaft is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Crankshaft. If not, see <http://www.gnu.org/licenses/>.

set -e

case "$1" in
    configure)
        # Add crankshaft user to required groups for display access
        usermod -a -G video,input,render crankshaft 2>/dev/null || true
        
        # Reload systemd and enable service
        systemctl daemon-reload
        systemctl enable crankshaft-ui.service
        
        echo "Crankshaft UI installed successfully"
        echo "Service enabled and will start on boot"
        echo "To start now: sudo systemctl start crankshaft-ui"
        echo "Note: crankshaft-core must be running first"
    ;;
esac

exit 0
