#!/usr/bin/env python3
# Project: Crankshaft
# This file is part of Crankshaft project.
# Copyright (C) 2025 OpenCarDev Team
#
#  Crankshaft is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Crankshaft is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Crankshaft. If not, see <http://www.gnu.org/licenses/>.

"""Small CLI to create and validate profile and config JSON files.

Usage examples:
  python docs/tools/profile_cli.py validate --type host --file /path/to/host_profiles.json
  python docs/tools/profile_cli.py create-host --name "Dev Host" --out ./host_profiles.json

This tool uses `jsonschema` for validation. Install dependencies with:
  pip install -r docs/tools/requirements.txt
"""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from datetime import datetime
from pathlib import Path

try:
    import jsonschema
except Exception:  # pragma: no cover - runtime check
    jsonschema = None


REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMAS_DIR = REPO_ROOT / "docs" / "schemas"


def load_schema(name: str) -> dict:
    path = SCHEMAS_DIR / f"{name}.schema.json"
    if not path.exists():
        raise FileNotFoundError(f"Schema not found: {path}")
    return json.loads(path.read_text())


def validate_file(schema_name: str, data_path: Path) -> int:
    if jsonschema is None:
        print("jsonschema package not installed. Install with: pip install -r docs/tools/requirements.txt")
        return 2

    schema = load_schema(schema_name)
    data = json.loads(data_path.read_text())

    validator = jsonschema.Draft7Validator(schema)
    errors = list(validator.iter_errors(data))
    if not errors:
        print(f"OK: {data_path} validates against {schema_name}.schema.json")
        return 0

    print(f"Validation errors in {data_path}:")
    for e in errors:
        print(f" - {'.'.join(map(str, e.path))}: {e.message}")
    return 1


def iso_now() -> str:
    return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def create_host_template(name: str = "Development Host") -> dict:
    host_id = str(uuid.uuid4())
    created = iso_now()

    android = {
        "name": "AndroidAuto",
        "type": "AndroidAuto",
        "enabled": True,
        "useMock": True,
        "description": "Android Auto projection service",
        "settings": {
            "resolution": "1024x600",
            "fps": 30,
            "generateTestVideo": True,
            "channels.video": True,
            "channels.mediaAudio": True,
            "connectionMode": "auto",
            "wireless.enabled": False,
            "wireless.host": "",
            "wireless.port": 5277,
        },
    }

    bluetooth = {
        "name": "Bluetooth",
        "type": "Bluetooth",
        "enabled": True,
        "useMock": True,
        "description": "Bluetooth adapter",
    }

    host = {
        "id": host_id,
        "name": name,
        "description": "Generated by profile_cli",
        "isActive": True,
        "createdAt": created,
        "modifiedAt": created,
        "cpuModel": "Development CPU",
        "ramMB": 8192,
        "osVersion": "Development",
        "devices": [android, bluetooth],
    }
    return host


def create_vehicle_template(name: str = "Test Vehicle - Sedan") -> dict:
    vid = str(uuid.uuid4())
    created = iso_now()
    vehicle = {
        "id": vid,
        "name": name,
        "description": "Generated by profile_cli",
        "isActive": True,
        "createdAt": created,
        "modifiedAt": created,
        "make": "Test Make",
        "model": "Test Model",
        "year": "2025",
        "vin": "TEST000000000001",
        "licensePlate": "MOCK-001",
        "vehicleType": "car",
        "supportedModes": ["PARK", "REVERSE", "NEUTRAL", "DRIVE"],
        "hasAWD": True,
        "wheelCount": 4,
    }
    return vehicle


def write_json_file(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def main(argv=None):
    p = argparse.ArgumentParser(description="Profile create/validate CLI for Crankshaft")
    sub = p.add_subparsers(dest="cmd")

    v = sub.add_parser("validate", help="Validate a JSON file against built-in schemas")
    v.add_argument("--type", choices=["host", "vehicle", "config"], required=True, help="Which schema to use")
    v.add_argument("--file", type=Path, required=True, help="Path to JSON file to validate")

    ch = sub.add_parser("create-host", help="Create a host profile JSON file (single element array) for editing")
    ch.add_argument("--name", default="Development Host")
    ch.add_argument("--out", type=Path, required=True, help="Output path for host_profiles.json")

    cv = sub.add_parser("create-vehicle", help="Create a vehicle profile JSON file (single element array)")
    cv.add_argument("--name", default="Test Vehicle - Sedan")
    cv.add_argument("--out", type=Path, required=True, help="Output path for vehicle_profiles.json")

    vr = sub.add_parser("validate-repo", help="Validate profiles found in a repo config directory (default: ./config)")
    vr.add_argument("--dir", type=Path, default=None, help="Directory that contains host_profiles.json and vehicle_profiles.json (defaults to ./config)")

    args = p.parse_args(argv)
    if args.cmd == "validate":
        mapping = {"host": "host_profiles", "vehicle": "vehicle_profiles", "config": "crankshaft_config"}
        schema_name = mapping[args.type]
        rc = validate_file(schema_name, args.file)
        sys.exit(rc)

    if args.cmd == "create-host":
        host = create_host_template(args.name)
        write_json_file(args.out, [host])
        print(f"Wrote host profile to: {args.out}")
        return

    if args.cmd == "create-vehicle":
        vehicle = create_vehicle_template(args.name)
        write_json_file(args.out, [vehicle])
        print(f"Wrote vehicle profile to: {args.out}")
        return

    if args.cmd == "validate-repo":
        base = args.dir if args.dir is not None else (Path.cwd() / "config")
        rc_total = 0
        host_path = base / "host_profiles.json"
        vehicle_path = base / "vehicle_profiles.json"
        if host_path.exists():
            print(f"Validating host profiles at: {host_path}")
            rc = validate_file("host_profiles", host_path)
            rc_total |= rc
        else:
            print(f"No host_profiles.json found at: {host_path}")

        if vehicle_path.exists():
            print(f"Validating vehicle profiles at: {vehicle_path}")
            rc = validate_file("vehicle_profiles", vehicle_path)
            rc_total |= rc
        else:
            print(f"No vehicle_profiles.json found at: {vehicle_path}")

        if rc_total == 0:
            print("Repository profiles validation: OK")
        else:
            print("Repository profiles validation: FAILED")
        sys.exit(0 if rc_total == 0 else 1)

    p.print_help()


if __name__ == "__main__":
    main()
